### ISSUE TITLE
pip3 install python-magento

### ISSUE THREAD

**Issue by rrwt** [bernieke/python-magento#12]
I am getting the following error during library installation:

Exception:
Traceback (most recent call last):
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/wheel.py", line 492, in move_wheel_files
    maker.make_multiple(['%s = %s' % kv for kv in console.items()])
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
    filenames.extend(self.make(specification, options))
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 368, in make
    entry = get_export_entry(specification)
  File "/Users/rohit.rawat/.virtualenvs/re_inv/lib/python3.5/site-packages/pip/_vendor/distlib/util.py", line 590, in get_export_entry
    "'%s'" % specification)
pip._vendor.distlib.DistlibException: Invalid specification 'magento-ipython-shell = magento.magento_ipython_shell:main [interactive-shell]'

**Comment by bernieke** [comment]
Fixed in 1.0.3
